"use client";
import { useMemo, useState } from "react";
import { PageTitle } from "@/components/app-shell";
import { RevenueChart, RiskChart, VolumeChart } from "@/components/charts";
import { DocumentPreviewCard, EmptyState, IntegrationCard, KpiCard, LoadingState, PermissionsTable, PricingCard, RiskBadge, StatusBadge, WorkflowCard } from "@/components/ui";
import { analyticsKpis, automationSavings } from "@/lib/mock-data/analytics";
import { billingHistory, plans, type PlanName, usageMetrics } from "@/lib/mock-data/billing";
import { documentQueue, extractedFields, knowledgeDocuments, validationChecks, type ApprovalState } from "@/lib/mock-data/documents";
import { integrations as initialIntegrations } from "@/lib/mock-data/integrations";
import { permissions, roles } from "@/lib/mock-data/roles";
import { workflows, type Workflow, type WorkflowPriority, type WorkflowStatus } from "@/lib/mock-data/workflows";
import { FileText, Search, Sparkles, UploadCloud, X } from "lucide-react";

export default function SectionClient({ section }: { section: string }) {
  if(section==="workflows")return <Workflows/>;
  if(section==="decisions")return <Decisions/>;
  if(section==="knowledge")return <Knowledge/>;
  if(section==="documents")return <Documents/>;
  if(section==="analytics")return <Analytics/>;
  if(section==="integrations")return <Integrations/>;
  if(section==="billing")return <Billing/>;
  if(section==="team")return <Team/>;
  return <EmptyState title="Page not found" body="Choose a workspace area from the navigation."/>;
}

function Workflows(){
  const [status,setStatus]=useState<"All"|WorkflowStatus>("All");
  const [priority,setPriority]=useState<"All"|WorkflowPriority>("All");
  const [reviewing,setReviewing]=useState<Workflow|null>(null);
  const filtered=useMemo(()=>workflows.filter(item=>(status==="All"||item.status===status)&&(priority==="All"||item.priority===priority)),[status,priority]);
  return <><PageTitle title="Financial workflows" subtitle="Monitor, prioritize, and advance work across every financial process." action="New workflow"/><div className="filter-groups"><div><span>Status</span>{(["All","In review","At risk","On track","Completed"] as const).map(item=><button key={item} onClick={()=>setStatus(item)} className={`filter ${status===item?"active":""}`}>{item}</button>)}</div><div><span>Priority</span>{(["All","High","Medium","Low"] as const).map(item=><button key={item} onClick={()=>setPriority(item)} className={`filter ${priority===item?"active":""}`}>{item}</button>)}</div></div>{filtered.length?<><div className="workflow-grid">{filtered.map(item=><WorkflowCard key={item.id} workflow={item} onReview={setReviewing}/>)}</div><div className="card table-card desktop-table"><table className="data-table"><thead><tr><th>Workflow</th><th>Status</th><th>Owner</th><th>Priority</th><th>Due</th><th>AI recommendation</th><th></th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><b>{item.name}</b><small>{item.id} · {item.type}</small></td><td><StatusBadge tone={item.status==="At risk"?"red":item.status==="In review"?"amber":item.status==="Completed"?"gray":"green"}>{item.status}</StatusBadge></td><td>{item.owner}</td><td><RiskBadge level={item.priority}/></td><td>{item.due}</td><td>{item.recommendation}</td><td><button className="action" onClick={()=>setReviewing(item)}>Review</button></td></tr>)}</tbody></table></div></>:<EmptyState title="No workflows found" body="Adjust the status or priority filters to see more work."/>}{reviewing&&<div className="modal-backdrop" onClick={()=>setReviewing(null)}><div className="modal" onClick={event=>event.stopPropagation()}><button className="modal-close" onClick={()=>setReviewing(null)}><X size={16}/></button><StatusBadge tone={reviewing.status==="At risk"?"red":"amber"}>{reviewing.status}</StatusBadge><h2>{reviewing.name}</h2><p>{reviewing.recommendation}</p><div className="modal-meta"><span><b>Owner</b>{reviewing.owner}</span><span><b>Due date</b>{reviewing.due}</span></div><button className="btn btn-dark full-button" onClick={()=>setReviewing(null)}>Open decision review</button></div></div>}</>;
}

function Decisions(){
  const [decision,setDecision]=useState<"Pending"|"Approved"|"Escalated">("Pending");
  return <><PageTitle title="AI decision support" subtitle="Prioritized financial signals with evidence, explanations, and human controls." action="Review queue"/><div className="decision-grid"><section className="card"><div className="card-head"><div><h2>Atlas Systems · Invoice INV-2408</h2><span>Payment decision · $186,420</span></div><StatusBadge tone={decision==="Approved"?"green":decision==="Escalated"?"red":"amber"}>{decision==="Pending"?"Approval required":decision}</StatusBadge></div><div className="risk-score"><div className="score-ring"><b>34</b></div><div><span className="micro-label">RISK SCORE · MODERATE</span><h3>Approve with payment-date adjustment</h3><p>No material vendor or document risk detected.</p></div></div><div className="recommendation-list">{[["Approve the invoice","PO, amount, tax, and receiving records match."],["Schedule for June 22","Preserves the operating buffer while remaining inside terms."],["Log policy exception","The invoice exceeds the reviewer’s standard approval threshold."]].map((item,index)=><div className="recommendation" key={item[0]}><span className="recommendation-num">{index+1}</span><div><h3>{item[0]}</h3><p>{item[1]}</p></div></div>)}</div><div className="document-actions"><button className="btn btn-dark" onClick={()=>setDecision("Approved")}>Approve recommendation</button><button className="btn btn-soft" onClick={()=>setDecision("Escalated")}>Escalate</button></div></section><section className="card"><div className="card-head"><h2>Why this recommendation</h2><StatusBadge>93% confidence</StatusBadge></div><div className="answer"><div className="answer-box"><b>Decision explanation</b><br/><br/>The invoice aligns with contracted pricing and the purchase order. Atlas Systems has a low exception rate across 18 prior payments. The proposed date balances vendor terms against the forecast cash threshold.<div className="citation">Evidence: Vendor Policy §4.2 · PO-88214 · Cash Forecast v18</div></div><div className="confidence"><span>Retrieval confidence</span><div className="confidence-bar"><i style={{width:"96%"}}/></div><b>96%</b></div><div className="confidence"><span>Policy fit</span><div className="confidence-bar"><i style={{width:"89%"}}/></div><b>89%</b></div></div></section></div></>;
}

function Knowledge(){
  const [query,setQuery]=useState("What is our approval policy for invoices over $100,000?");
  const [searched,setSearched]=useState(query);
  const hasResult=/invoice|approval|billing|policy/i.test(searched);
  return <><PageTitle title="Knowledge hub" subtitle="Ground AI decisions in approved company policies, procedures, and financial context." action="Upload sources"/><form className="knowledge-search" onSubmit={event=>{event.preventDefault();setSearched(query);}}><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} aria-label="Search knowledge base"/><button className="btn btn-dark">Search knowledge</button></form><div className="doc-grid"><section className="card"><div className="card-head"><h2>Approved sources</h2><span>{knowledgeDocuments.length} featured · 43 total</span></div><div className="doc-list">{knowledgeDocuments.map(document=><div className="doc-item" key={document.name}><span className="file-icon"><FileText size={15}/></span><div><b>{document.name}</b><span>{document.category} · {document.updated}</span></div></div>)}</div></section><section className="card"><div className="card-head"><h2>Grounded answer</h2>{hasResult&&<StatusBadge>95% retrieval confidence</StatusBadge>}</div>{!searched.trim()?<EmptyState title="Ask the knowledge base" body="Search approved company sources to generate a cited answer."/>:hasResult?<div className="answer"><div className="answer-box"><span className="insight-label"><Sparkles size={12}/> Answer from approved knowledge</span><br/>Invoices above $100,000 require approval from both the Finance Manager and a designated Admin. Non-PO invoices also require Compliance review before payment scheduling.<div className="citation"><b>Billing Rules 2026 · §3.4</b><br/>Dual approval is required for payments exceeding the delegated threshold.</div><div className="citation"><b>Compliance Controls · §8.1</b><br/>Non-PO invoices above threshold must be routed for control review.</div></div></div>:<EmptyState title="No approved answer found" body="Try a question about invoice approvals, billing rules, or company policy."/>}</section></div></>;
}

function Documents(){
  const [approval,setApproval]=useState<ApprovalState>("Needs review");
  const [uploading,setUploading]=useState(false);
  const [uploaded,setUploaded]=useState(false);
  const upload=()=>{setUploading(true);setTimeout(()=>{setUploading(false);setUploaded(true);setApproval("Needs review");},900);};
  return <><PageTitle title="Document processing" subtitle="Ingest, validate, extract, and approve financial documents." action="Upload document"/><div className="doc-grid"><section className="card"><div className="card-head"><h2>New document</h2><span>Invoice · Contract · Statement · Compliance</span></div>{uploading?<LoadingState label="Processing uploaded document..."/>:<button className="upload upload-button" onClick={upload}><UploadCloud size={25}/><b>{uploaded?"Upload another document":"Choose a mock financial document"}</b><span>PDF, DOCX, PNG, or XLSX · up to 25 MB</span></button>}<div className="card-head"><h2>Processing queue</h2></div><div className="doc-list">{documentQueue.map((document,index)=><div className="doc-item" key={document.name}><span className="file-icon"><FileText size={15}/></span><div className="grow"><b>{document.name}</b><span>Uploaded today</span></div><StatusBadge tone={index===0?(approval==="Approved"?"green":approval==="Rejected"?"red":"amber"):document.tone}>{index===0?approval:document.state}</StatusBadge></div>)}</div></section><DocumentPreviewCard approval={approval} onApprove={()=>setApproval("Approved")} onReject={()=>setApproval("Rejected")} fields={extractedFields} checks={validationChecks}/></div></>;
}

function Analytics(){return <><PageTitle title="Analytics" subtitle="Commercial, operational, and AI performance in one reporting layer." action="Export report"/><div className="kpi-grid">{analyticsKpis.map(item=><KpiCard key={item.label} {...item}/>)}</div><div className="dashboard-grid"><section className="card"><div className="card-head"><h2>Revenue growth</h2><span>7-month recognized revenue</span></div><div className="chart-wrap"><RevenueChart/></div></section><section className="card"><div className="card-head"><h2>Risk trend</h2><span>Low vs. elevated flags</span></div><div className="chart-wrap"><RiskChart/></div></section></div><div className="dashboard-grid"><section className="card"><div className="card-head"><h2>Document volume</h2><span>1,086 processed this week</span></div><div className="chart-wrap"><VolumeChart/></div></section><section className="card"><div className="card-head"><h2>Automation value</h2><span>Current month</span></div><div className="activity">{automationSavings.map(item=><div className="activity-row" key={item.name}><span className="activity-icon"><Sparkles size={13}/></span><div><b>{item.name}</b><p>{item.hours} saved</p></div><b>{item.value}</b></div>)}</div></section></div></>;}

function Integrations(){
  const [items,setItems]=useState(initialIntegrations);
  const [category,setCategory]=useState("All");
  const visible=items.filter(item=>category==="All"||item.category===category);
  const toggle=(name:string)=>setItems(current=>current.map(item=>item.name===name?{...item,connected:!item.connected}:item));
  return <><PageTitle title="Integration hub" subtitle="Connect the systems your finance operation already depends on." action="Request integration"/><div className="filters">{["All","Accounting","Banking","Documents","Communication","Payments"].map(item=><button onClick={()=>setCategory(item)} className={`filter ${category===item?"active":""}`} key={item}>{item}</button>)}</div>{visible.length?<div className="integration-grid">{visible.map(item=><IntegrationCard key={item.name} integration={item} onToggle={()=>toggle(item.name)}/>)}</div>:<EmptyState title="No integrations connected" body="Select another category or connect a secure provider."/ >}</>;
}

function Billing(){
  const [selected,setSelected]=useState<PlanName>("Enterprise");
  return <><PageTitle title="Subscription & billing" subtitle="Manage workspace plan, usage, invoices, and payment status." action="Manage payment"/><section className="card subscription-summary"><div><StatusBadge>Active subscription</StatusBadge><h2>{selected} Operations</h2><p>Renews annually on January 12, 2027 · Visa ending 8824</p></div><div className="health-indicator"><span>Subscription health</span><b>94</b><small>Healthy</small></div></section><div className="pricing-grid pricing-three">{plans.map(plan=><PricingCard key={plan.name} {...plan} selected={selected===plan.name} current={plan.name==="Enterprise"} onSelect={()=>setSelected(plan.name)}/>)}</div><h2 className="section-title">Usage this billing period</h2><div className="kpi-grid">{usageMetrics.map(item=><div className="card kpi" key={item.label}><div className="kpi-top">{item.label}</div><div className="kpi-value compact-value">{item.value}</div><div className="confidence-bar"><i style={{width:`${item.progress}%`}}/></div></div>)}</div><div className="card table-card billing-table"><div className="card-head"><h2>Billing history</h2><span>Payment status</span></div>{billingHistory.length?<table className="data-table"><thead><tr><th>Invoice</th><th>Billing period</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{billingHistory.map(item=><tr key={item.invoice}><td><b>{item.invoice}</b></td><td>{item.period}</td><td>{item.amount}</td><td><StatusBadge>{item.status}</StatusBadge></td><td><button className="action">Download</button></td></tr>)}</tbody></table>:<EmptyState title="No billing history" body="Paid invoices will appear here after the first billing cycle."/>}</div></>;
}

function Team(){return <><PageTitle title="Team & roles" subtitle="Control access with role-based permissions and auditable assignments." action="Invite team member"/><div className="kpi-grid">{[["Active members","38","2 pending"],["Roles configured","6","Policy based"],["SSO coverage","100%","Enforced"],["Access reviews","2 due","Jun 30"]].map(item=><KpiCard key={item[0]} label={item[0]} value={item[1]} trend={item[2]}/>)}</div><div className="team-table"><PermissionsTable roles={roles} permissions={permissions}/></div></>;}
